### ISSUE TITLE
Decide on whether we will use ERC 725 or our own approach for smart contract identity permissions

### ISSUE THREAD

**Issue by matthewliu** [OriginProtocol/platform#59]

**Comment by joshfraser** [comment]
We've decided to go with ERC 725 with the following plan:

1) We will support and encourage the batching of attestations to save on gas
2) We have the verifier return the signed attestation, so that the requestor pays gas (protects the verifier from wallet draining attacks)
3) We will deploy the personal identity contract, submit batched claims & add them to user registry in one step 

We have a cool opportunity to be the first live implementation of ERC 725!!  Let's make it count.
