### ISSUE TITLE
Create sample listings for testing

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/platform#93]
We took the 4 standard sample listings out of `ListingsRegistry` because (1) that's dumb and (2) it blew up our gas costs. 

The right way it to make it part of our migrations. 

@Jannis provided a great Gist with this explanation:

> If you drop this file in migrations/, update the contract address at the top and run truffle migrate, you'll have 238 listings with ~50% having a random number of purchases between 1 and the number of units available.

https://gist.github.com/Jannis/58fff8213cd8a2ffe9a7ec55115ea598

**Comment by tyleryasaka** [comment]
@wanderingstan Have you seen the seed script? https://github.com/OriginProtocol/platform/blob/develop/packages/contracts/scripts/seed.js

Instructions for seeding data in readme: https://github.com/OriginProtocol/platform/tree/develop/packages/contracts#using-seed-data

I'm all for modifying that script to have more listings, better data, etc in accordance with that gist.

However I would make the case that it's better to put it in a separate seed script rather than make it a migration. I think creating sample data is out of the scope of migrations. Migrations should only contain things that should run in production.

**Comment by wanderingstan** [comment]
Wow @tyleryasaka , I had **not** seen your seed script but that looks to do exactly what this issue is about. 

However when I run it, I get an error. I'll investigate more later. (Hopping on bus now)
```
truffle(develop)> exec scripts/seed.js
Using network 'develop'.

module.js:559
    throw err;
    ^

Error: Cannot find module 'truffle-contract'
    at Function.Module._resolveFilename (module.js:557:15)
    at Function.Module._load (module.js:484:25)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
    at require (/Users/stan/Origin/platform/packages/contracts/node_modules/truffle/build/cli.bundled.js:125898:20)
    at /Users/stan/Origin/platform/packages/contracts/scripts/seed.js:2:16
    at Script.runInContext (vm.js:74:29)
    at Script.runInNewContext (vm.js:80:15)
    at /Users/stan/Origin/platform/packages/contracts/node_modules/truffle/build/cli.bundled.js:125917:14
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:532:3)
```

**Comment by tyleryasaka** [comment]
@wanderingstan I think you just need to run `npm install` inside the `contracts` package. I added that dependency and you probably haven't rerun the install since then. 😃

**Comment by wanderingstan** [comment]
Bingo! That did it. 

I would love for these listings to show up in our "one line setup" for the DApp. I.e., they download `demo-dapp`, run it, and --voila!-- they see some nice sample listings. Can you think of the best way to do that? (Or that might be topic for a separate issue) 

https://github.com/OriginProtocol/platform/issues/89

I'll close this one out!
